# -*- coding: utf-8 -*-
"""Part_2_Product_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZLi_FXol_imgu8wK95OjqHZruXAY5Z7
"""

import torch
import torchvision
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from torchvision import datasets, transforms

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)

class_names = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]

train_dataset = datasets.FashionMNIST(
    root="/content/data",
    train=True,
    download=True
)

test_dataset = datasets.FashionMNIST(
    root="/content/data",
    train=False,
    download=True
)

from sklearn.model_selection import StratifiedShuffleSplit
from torch.utils.data import Subset

random_seed = 42
num_train = 55000
num_validation = 5000

targets = train_dataset.targets.numpy()

test_size_ratio = num_validation / (num_train + num_validation)

sss = StratifiedShuffleSplit(n_splits=1, test_size=test_size_ratio, random_state=random_seed)

for train_index, validation_index in sss.split(np.zeros(len(targets)), targets):
    pass
train_data = Subset(train_dataset, train_index)
validation_data = Subset(train_dataset, validation_index)

print(f"Training images after split: {len(train_data)}")
print(f"Validation images: {len(validation_data)}")
print(f"Test images: {len(test_dataset)}")

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("Transform created successfully.")

train_dataset_transformed = datasets.FashionMNIST(
    root="/content/data",
    train=True,
    download=True,
    transform=transform
)

test_dataset_transformed = datasets.FashionMNIST(
    root="/content/data",
    train=False,
    download=True,
    transform=transform
)

print("Transformed datasets ready.")

from torch.utils.data import Subset

train_subset = Subset(
    train_dataset_transformed,
    train_index
)

val_subset = Subset(
    train_dataset_transformed,
    validation_index
)

print("Train subset:", len(train_subset))
print("Validation subset:", len(val_subset))

from torch.utils.data import DataLoader

batch_size = 128

train_loader = DataLoader(
    train_subset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_subset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset_transformed,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("DataLoaders created.")

images, labels_batch = next(iter(train_loader))

print("Image shape:", images.shape)
print("Labels shape:", labels_batch.shape)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", device)

import torch
from torchvision.models import resnet18, ResNet18_Weights

weights = ResNet18_Weights.DEFAULT

model = resnet18(weights=weights)

print("Pretrained ResNet-18 loaded.")

for param in model.parameters():
    param.requires_grad = False

print("ResNet-18 backbone frozen.")

import torch.nn as nn

num_features = model.fc.in_features

model.fc = nn.Linear(
    num_features,
    10
)

model = model.to(device)

print(model.fc)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.fc.parameters(),
    lr=0.001
)

print("Loss and optimizer ready.")

num_epochs = 5

for epoch in range(num_epochs):

    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels_batch in train_loader:

        images = images.to(device)
        labels_batch = labels_batch.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels_batch)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)

        total += labels_batch.size(0)
        correct += (predicted == labels_batch).sum().item()

    train_accuracy = 100 * correct / total

    print(
        f"Epoch [{epoch+1}/{num_epochs}] "
        f"Loss: {running_loss/len(train_loader):.4f} "
        f"Train Accuracy: {train_accuracy:.2f}%"
    )

def evaluate_accuracy(model, loader):

    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels_batch in loader:

            images = images.to(device)
            labels_batch = labels_batch.to(device)

            outputs = model(images)

            _, predicted = torch.max(outputs, 1)

            total += labels_batch.size(0)
            correct += (predicted == labels_batch).sum().item()

    return 100 * correct / total


validation_accuracy_before = evaluate_accuracy(
    model,
    val_loader
)

print(
    f"Validation accuracy before fine-tuning: "
    f"{validation_accuracy_before:.2f}%"
)

test_accuracy = evaluate_accuracy(
    model,
    test_loader
)

print(f"Final test accuracy: {test_accuracy:.2f}%")

model.eval()

all_predictions = []
all_true_labels = []

with torch.no_grad():

    for images, labels_batch in test_loader:

        images = images.to(device)

        outputs = model(images)

        _, predictions = torch.max(outputs, 1)

        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_true_labels.extend(
            labels_batch.numpy()
        )

print("Number of predictions:", len(all_predictions))
print("Number of true labels:", len(all_true_labels))

print("First 10 actual labels:")
print(all_true_labels[:10])

print("\nFirst 10 predicted labels:")
print(all_predictions[:10])

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    all_true_labels,
    all_predictions
)
print("Confusion matrix shape:", cm.shape)
print(cm)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names
)

fig, ax = plt.subplots(figsize=(10, 10))

disp.plot(
    ax=ax,
    xticks_rotation=45
)

plt.title("Fashion-MNIST Confusion Matrix")
plt.tight_layout()
plt.show()

cm_df = pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names
)

print(cm_df)

cm_df.to_csv(
    "/content/confusion_matrix.csv"
)

print("Confusion matrix saved.")

from sklearn.metrics import classification_report

report = classification_report(
    all_true_labels,
    all_predictions,
    target_names=class_names,
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

print(report_df)

report_df.to_csv(
    "/content/classification_report.csv"
)

print("Classification report saved.")

import numpy as np

cm_without_diagonal = cm.copy()

# Remove correct predictions
np.fill_diagonal(cm_without_diagonal, 0)

# Sort all remaining values from largest to smallest
flat_indices = np.argsort(
    cm_without_diagonal.ravel()
)[::-1]

print("Top confusion pairs:\n")

count = 0

for index in flat_indices:

    actual_class, predicted_class = np.unravel_index(
        index,
        cm.shape
    )

    confusion_count = cm[
        actual_class,
        predicted_class
    ]

    if confusion_count == 0:
        continue

    print(
        f"{class_names[actual_class]} "
        f"-> "
        f"{class_names[predicted_class]}: "
        f"{confusion_count}"
    )

    count += 1

    if count == 5:
        break

import os

os.makedirs(
    "/content/models",
    exist_ok=True
)

model_path = "/content/models/product_classifier.pt"

torch.save(
    model.state_dict(),
    model_path
)

print("Model saved at:")
print(model_path)

import os

model_path = "/content/models/product_classifier.pt"

print(
    "File exists:",
    os.path.exists(model_path)
)

if os.path.exists(model_path):

    print(
        "File size:",
        os.path.getsize(model_path),
        "bytes"
    )

def load_product_classifier(model_path, device):

    weights = ResNet18_Weights.DEFAULT

    model = resnet18(weights=weights)

    num_features = model.fc.in_features

    model.fc = nn.Linear(
        num_features,
        10
    )

    model.load_state_dict(
        torch.load(
            model_path,
            map_location=device
        )
    )

    model.to(device)
    model.eval()

    return model

loaded_model = load_product_classifier(
    "/content/models/product_classifier.pt",
    device
)

print("Saved model loaded successfully.")

from PIL import Image

def predict_product_image(
    image_path,
    model,
    transform,
    class_names,
    device
):

    image = Image.open(image_path).convert("L")

    image = transform(image)

    image = image.unsqueeze(0).to(device)

    with torch.no_grad():

        outputs = model(image)

        probabilities = torch.softmax(
            outputs,
            dim=1
        )

        predicted_class = torch.argmax(
            probabilities,
            dim=1
        ).item()

    return {
        "class": class_names[predicted_class],
        "confidence": float(
            probabilities[0, predicted_class]
        )
    }

import os

sample_dir = "/content/sample_images"

os.makedirs(
    sample_dir,
    exist_ok=True
)

print("Sample image folder created.")

selected_indices = [0, 1, 2, 3, 4]

for i, index in enumerate(selected_indices):

    image, label = test_dataset[index]

    filename = (
        f"{i+1:02d}_"
        f"{class_names[label].lower().replace('/', '_').replace(' ', '_')}.png"
    )

    save_path = os.path.join(
        sample_dir,
        filename
    )

    image.save(save_path)

    print("Saved:", filename)

sample_files = os.listdir(sample_dir)

print(
    "Number of sample images:",
    len(sample_files)
)

for file in sample_files:
    print(file)

fig, axes = plt.subplots(
    1,
    5,
    figsize=(15, 3)
)

for i, file in enumerate(sample_files):

    image = Image.open(
        os.path.join(sample_dir, file)
    )

    axes[i].imshow(
        image,
        cmap="gray"
    )

    axes[i].set_title(file[:12])
    axes[i].axis("off")

plt.tight_layout()
plt.show()

first_image = os.path.join(
    sample_dir,
    sample_files[0]
)

result = predict_product_image(
    first_image,
    loaded_model,
    transform,
    class_names,
    device
)

print(result)

for file in sample_files:

    image_path = os.path.join(
        sample_dir,
        file
    )

    result = predict_product_image(
        image_path,
        loaded_model,
        transform,
        class_names,
        device
    )

    print(
        file,
        "->",
        result
    )

from google.colab import files

files.download("/content/models/product_classifier.pt")

from google.colab import files

files.download("/content/confusion_matrix.csv")

from google.colab import files

files.download("/content/classification_report.csv")

import shutil

shutil.make_archive(
    "/content/sample_images",
    "zip",
    "/content/sample_images"
)

print("ZIP created.")
from google.colab import files

files.download("/content/sample_images.zip")

from google.colab import files

files.download("/content/sample_images.zip")

from google.colab import files

files.download("/content/models/product_classifier.pt")