# -*- coding: utf-8 -*-
"""Part_1_Return_Risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDbjaaiXsG1MZ-Da8eGL1EIBCr5fhBTv
"""

import pandas as pd

url = "https://raw.githubusercontent.com/kartikgoel1126/flipkart-support/main/orders_dataset.csv"

df = pd.read_csv(url)

df.head()

print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

print("Column Names:")
for col in df.columns:
    print(f"- {col}")

df.info()

id_col = 'order_id'
target_col = 'returned'

numerical_features = [col for col in df.select_dtypes(include=['int64', 'float64']).columns.tolist() if col not in [id_col, target_col]]

categorical_features = df.select_dtypes(include=['object']).columns.tolist()

print(f"ID Column: {id_col}")
print(f"Target Column: {target_col}")

print("\nNumerical Features:")
for col in numerical_features:
    print(f"- {col}")

print("\nCategorical Features:")
for col in categorical_features:
    print(f"- {col}")

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

if not missing_values.empty:
    print("Columns with Missing Values:")
    display(missing_values.to_frame(name='Number of Missing Values'))
else:
    print("No missing values found in the dataset.")

overall_return_rate = df['returned'].mean() * 100

print(f"Overall Return Rate: {overall_return_rate:.2f}%")

return_rate_by_category = df.groupby('product_category')['returned'].mean().sort_values(ascending=False)
print("Return Rate by Product Category:")
display(return_rate_by_category.to_frame(name='Return Rate'))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(x=return_rate_by_category.index, y=return_rate_by_category.values * 100, palette='viridis')
plt.title('Return Rate by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Return Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

category_table = (
    df.groupby("product_category")["returned"]
    .agg(["count", "mean"])
    .reset_index()
)

category_table["return_rate_%"] = (
    category_table["mean"] * 100
).round(2)

category_table = category_table.drop(columns=["mean"])

display(category_table)

return_rate_by_payment = df.groupby('payment_method')['returned'].mean().sort_values(ascending=False)
print("Return Rate by Payment Method:")
display(return_rate_by_payment.to_frame(name='Return Rate'))

plt.figure(figsize=(10, 6))
sns.barplot(x=return_rate_by_payment.index, y=return_rate_by_payment.values * 100, palette='magma')
plt.title('Return Rate by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Return Rate (%)')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

payment_table = (
    df.groupby("payment_method")["returned"]
    .agg(["count", "mean"])
    .reset_index()
)

payment_table["return_rate_%"] = (
    payment_table["mean"] * 100
).round(2)

payment_table = payment_table.drop(columns=["mean"])

display(payment_table)

cod_df = df[df['payment_method'] == 'COD']
cod_missing_count = cod_df['rating_given'].isnull().sum()
cod_total_count = len(cod_df)
cod_missing_percentage = (cod_missing_count / cod_total_count) * 100 if cod_total_count > 0 else 0

print(f"COD Missing Count: {cod_missing_count}")
print(f"COD Total Count: {cod_total_count}")
print(f"COD Missing Percentage (Rating Given): {cod_missing_percentage:.2f}%")

non_cod_df = df[df['payment_method'] != 'COD']
non_cod_missing_count = non_cod_df['rating_given'].isnull().sum()
non_cod_total_count = len(non_cod_df)
non_cod_missing_percentage = (non_cod_missing_count / non_cod_total_count) * 100 if non_cod_total_count > 0 else 0

print(f"Non-COD Missing Count: {non_cod_missing_count}")
print(f"Non-COD Total Count: {non_cod_total_count}")
print(f"Non-COD Missing Percentage (Rating Given): {non_cod_missing_percentage:.2f}%")

gap_percentage = cod_missing_percentage - non_cod_missing_percentage

print(f"Gap in Missing Percentage (COD - Non-COD): {gap_percentage:.2f}%")

X = df.drop(columns=["returned", "order_id"])
y = df["returned"]

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("Numerical Features:")
for col in numerical_features:
    print(f"- {col}")

print("\nCategorical Features:")
for col in categorical_features:
    print(f"- {col}")

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

print("Numerical preprocessing pipeline created.")

from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

print("Categorical preprocessing pipeline created with imputation.")

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

print("Preprocessing ColumnTransformer created.")

from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyClassifier

model_pipeline_dummy = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DummyClassifier(strategy='most_frequent'))
])

print("DummyClassifier pipeline created.")

model_pipeline_dummy.fit(X_train, y_train)

print("DummyClassifier model trained.")

y_pred_dummy = model_pipeline_dummy.predict(X_test)

print("Predictions made with DummyClassifier.")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

accuracy_dummy = accuracy_score(y_test, y_pred_dummy)
precision_dummy = precision_score(y_test, y_pred_dummy)
recall_dummy = recall_score(y_test, y_pred_dummy)
f1_dummy = f1_score(y_test, y_pred_dummy)
roc_auc_dummy = roc_auc_score(y_test, y_pred_dummy)

print(f"DummyClassifier Accuracy: {accuracy_dummy:.4f}")
print(f"DummyClassifier Precision: {precision_dummy:.4f}")
print(f"DummyClassifier Recall: {recall_dummy:.4f}")
print(f"DummyClassifier F1-Score: {f1_dummy:.4f}")
print(f"DummyClassifier ROC AUC Score: {roc_auc_dummy:.4f}")

cm_dummy = confusion_matrix(y_test, y_pred_dummy)
print("\nDummyClassifier Confusion Matrix:")
print(cm_dummy)

from sklearn.linear_model import LogisticRegression
model_pipeline_lr = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42, solver='liblinear', class_weight='balanced')) # Using liblinear for small datasets and 'balanced' to handle imbalanced classes
])

print("Logistic Regression pipeline created.")

model_pipeline_lr.fit(X_train, y_train)

print("Logistic Regression model trained.")

y_pred_lr = model_pipeline_lr.predict(X_test)
y_proba_lr = model_pipeline_lr.predict_proba(X_test)[:, 1]

print("Predictions made with Logistic Regression.")

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_proba_lr)

print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")
print(f"Logistic Regression Precision: {precision_lr:.4f}")
print(f"Logistic Regression Recall: {recall_lr:.4f}")
print(f"Logistic Regression F1-Score: {f1_lr:.4f}")
print(f"Logistic Regression ROC AUC Score: {roc_auc_lr:.4f}")

cm_lr = confusion_matrix(y_test, y_pred_lr)
print("\nLogistic Regression Confusion Matrix:")
print(cm_lr)

print(f"Logistic Regression Accuracy (Threshold 0.5): {accuracy_lr:.4f}")
print(f"Logistic Regression Precision (Threshold 0.5): {precision_lr:.4f}")
print(f"Logistic Regression Recall (Threshold 0.5): {recall_lr:.4f}")
print(f"Logistic Regression F1-Score (Threshold 0.5): {f1_lr:.4f}")
print(f"Logistic Regression ROC AUC Score (Threshold 0.5): {roc_auc_lr:.4f}")

print("\nLogistic Regression Confusion Matrix (Threshold 0.5):")
print(cm_lr)

import numpy as np

thresholds = np.arange(0.1, 1.0, 0.05)

results = []
for t in thresholds:

    y_pred_threshold = (y_proba_lr >= t).astype(int)

    precision = precision_score(y_test, y_pred_threshold, zero_division=0)
    recall = recall_score(y_test, y_pred_threshold, zero_division=0)
    f1 = f1_score(y_test, y_pred_threshold, zero_division=0)

    results.append({
        'Threshold': t,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1
    })

threshold_df = pd.DataFrame(results)
display(threshold_df)

best_f1_threshold = threshold_df.loc[threshold_df['F1-Score'].idxmax()]
print(f"\nBest Threshold based on F1-Score:\n{best_f1_threshold}")

plt.figure(figsize=(10, 6))
sns.lineplot(x='Threshold', y='F1-Score', data=threshold_df, marker='o')
plt.title('F1-Score vs. Classification Threshold for Logistic Regression')
plt.xlabel('Threshold')
plt.ylabel('F1-Score')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(np.arange(0.1, 1.0, 0.05), rotation=45)
plt.axvline(x=best_f1_threshold['Threshold'], color='r', linestyle='--', label=f'Best F1 Threshold: {best_f1_threshold["Threshold"]:.2f}')
plt.legend()
plt.tight_layout()
plt.show()

optimal_threshold = best_f1_threshold['Threshold']

y_pred_optimal = (y_proba_lr >= optimal_threshold).astype(int)

accuracy_optimal = accuracy_score(y_test, y_pred_optimal)
precision_optimal = precision_score(y_test, y_pred_optimal, zero_division=0)
recall_optimal = recall_score(y_test, y_pred_optimal, zero_division=0)
f1_optimal = f1_score(y_test, y_pred_optimal, zero_division=0)

comparison_data = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'Threshold'],
    'Default Threshold (0.5)': [
        accuracy_lr,
        precision_lr,
        recall_lr,
        f1_lr,
        0.5
    ],
    'Optimized Threshold (0.45)': [
        accuracy_optimal,
        precision_optimal,
        recall_optimal,
        f1_optimal,
        optimal_threshold
    ]
}

comparison_df = pd.DataFrame(comparison_data)
display(comparison_df.round(4))

print(f"\nConfusion Matrix at Optimized Threshold ({optimal_threshold:.2f}):")
display(confusion_matrix(y_test, y_pred_optimal))

from sklearn.ensemble import RandomForestClassifier

model_pipeline_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, class_weight='balanced'))
])

print("Random Forest pipeline created.")

model_pipeline_rf.fit(X_train, y_train)

print("Random Forest model trained.")

y_pred_rf = model_pipeline_rf.predict(X_test)
y_proba_rf = model_pipeline_rf.predict_proba(X_test)[:, 1]

print("Predictions made with Random Forest.")

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_auc_rf = roc_auc_score(y_test, y_proba_rf)

print(f"Random Forest Accuracy: {accuracy_rf:.4f}")
print(f"Random Forest Precision: {precision_rf:.4f}")
print(f"Random Forest Recall: {recall_rf:.4f}")
print(f"Random Forest F1-Score: {f1_rf:.4f}")
print(f"Random Forest ROC AUC Score: {roc_auc_rf:.4f}")

cm_rf = confusion_matrix(y_test, y_pred_rf)
print("\nRandom Forest Confusion Matrix:")
print(cm_rf)

from sklearn.model_selection import GridSearchCV, StratifiedKFold

param_grid_rf = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [10, 20, None],
    'classifier__min_samples_split': [2, 5],
    'classifier__min_samples_leaf': [1, 2]
}

print("Random Forest parameter grid created.")

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("5-fold StratifiedKFold created.")

grid_search_rf = GridSearchCV(
    estimator=model_pipeline_rf,
    param_grid=param_grid_rf,
    cv=skf,
    scoring='f1',
    n_jobs=-1,
    verbose=2
)

print("GridSearchCV object for Random Forest created.")

print("Starting GridSearchCV fit...")
grid_search_rf.fit(X_train, y_train)
print("GridSearchCV fit complete.")

print("\nBest parameters found:")
print(grid_search_rf.best_params_)
print("\nBest F1-score:")
print(f"{grid_search_rf.best_score_:.4f}")

best_rf_model = grid_search_rf.best_estimator_
print("\nBest Random Forest model obtained from GridSearchCV.")

y_pred_rf_tuned = best_rf_model.predict(X_test)

y_proba_rf_tuned = best_rf_model.predict_proba(X_test)[:, 1]

print("Predictions and probabilities made using the best Random Forest model.")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

accuracy_rf_tuned = accuracy_score(y_test, y_pred_rf_tuned)
precision_rf_tuned = precision_score(y_test, y_pred_rf_tuned, zero_division=0)
recall_rf_tuned = recall_score(y_test, y_pred_rf_tuned, zero_division=0)
f1_rf_tuned = f1_score(y_test, y_pred_rf_tuned, zero_division=0)
roc_auc_rf_tuned = roc_auc_score(y_test, y_proba_rf_tuned)

print(f"Best Random Forest Model Accuracy: {accuracy_rf_tuned:.4f}")
print(f"Best Random Forest Model Precision: {precision_rf_tuned:.4f}")
print(f"Best Random Forest Model Recall: {recall_rf_tuned:.4f}")
print(f"Best Random Forest Model F1-Score: {f1_rf_tuned:.4f}")
print(f"Best Random Forest Model ROC AUC Score: {roc_auc_rf_tuned:.4f}")

cm_rf_tuned = confusion_matrix(y_test, y_pred_rf_tuned)
print("\nBest Random Forest Model Confusion Matrix:")
print(cm_rf_tuned)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns

fpr, tpr, thresholds = roc_curve(y_test, y_proba_rf_tuned)

roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
sns.lineplot(x=fpr, y=tpr)
plt.plot([0, 1], [0, 1], color='navy', linestyle='--', label='Random (AUC = 0.50)')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title(f'ROC Curve for Tuned Random Forest (AUC = {roc_auc:.2f})')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds_rf = np.arange(0.1, 1.0, 0.05)

results_rf_tuned = []
for t in thresholds_rf:

    y_pred_threshold_rf_tuned = (y_proba_rf_tuned >= t).astype(int)

    precision_rf_t_tuned = precision_score(y_test, y_pred_threshold_rf_tuned, zero_division=0)
    recall_rf_t_tuned = recall_score(y_test, y_pred_threshold_rf_tuned, zero_division=0)
    f1_rf_t_tuned = f1_score(y_test, y_pred_threshold_rf_tuned, zero_division=0)

    results_rf_tuned.append({
        'Threshold': t,
        'Precision': precision_rf_t_tuned,
        'Recall': recall_rf_t_tuned,
        'F1-Score': f1_rf_t_tuned
    })

threshold_df_rf_tuned = pd.DataFrame(results_rf_tuned)
display(threshold_df_rf_tuned)

best_f1_threshold_rf_tuned = threshold_df_rf_tuned.loc[threshold_df_rf_tuned['F1-Score'].idxmax()]
optimal_threshold_rf_tuned = best_f1_threshold_rf_tuned['Threshold']

print(f"\nBest Threshold based on F1-Score for Tuned Random Forest:\nThreshold: {optimal_threshold_rf_tuned:.2f}\nF1-Score: {best_f1_threshold_rf_tuned['F1-Score']:.4f}\nPrecision: {best_f1_threshold_rf_tuned['Precision']:.4f}\nRecall: {best_f1_threshold_rf_tuned['Recall']:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(x='Threshold', y='F1-Score', data=threshold_df_rf_tuned, marker='o')
plt.title('F1-Score vs. Classification Threshold for Tuned Random Forest')
plt.xlabel('Threshold')
plt.ylabel('F1-Score')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(np.arange(0.1, 1.0, 0.05), rotation=45)
plt.axvline(x=optimal_threshold_rf_tuned, color='r', linestyle='--', label=f'Best F1 Threshold: {optimal_threshold_rf_tuned:.2f}')
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np

feature_names = numerical_features

onehot_encoder = best_rf_model.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot']
categorical_feature_names = onehot_encoder.get_feature_names_out(categorical_features)

all_feature_names = np.concatenate([feature_names, categorical_feature_names])

rf_classifier = best_rf_model.named_steps['classifier']

importances = rf_classifier.feature_importances_

feature_importances_df = pd.DataFrame({
    'Feature': all_feature_names,
    'Importance': importances
})

feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)
display(feature_importances_df.head(10))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=feature_importances_df.head(10), palette='viridis')
plt.title('Top 10 Feature Importances (Tuned Random Forest)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=feature_importances_df.head(10), palette='viridis')
plt.title('Top 10 Feature Importances (Tuned Random Forest)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.inspection import permutation_importance
import pandas as pd
import numpy as np

print("Calculating permutation importance...")

preprocessor_step = best_rf_model.named_steps['preprocessor']
classifier_step = best_rf_model.named_steps['classifier']

X_test_transformed = preprocessor_step.transform(X_test)

feature_names_for_importance = preprocessor_step.get_feature_names_out()

perm_importance = permutation_importance(
    classifier_step, X_test_transformed, y_test, n_repeats=10, random_state=42, n_jobs=1
)

print(f"Length of feature_names_for_importance: {len(feature_names_for_importance)}")
print(f"Length of perm_importance.importances_mean: {len(perm_importance.importances_mean)}")

perm_df = pd.DataFrame({
    'Feature': feature_names_for_importance,
    'Importance_Mean': perm_importance.importances_mean,
    'Importance_Std': perm_importance.importances_std
})

perm_df = perm_df.sort_values(by='Importance_Mean', ascending=False)

print("Permutation importance calculated.")

display(perm_df.head(10))

top_5_perm_features = perm_df['Feature'].head(5).tolist()

print("Top 5 features based on permutation importance:")
for feature in top_5_perm_features:
    print(f"- {feature}")

display(feature_importances_df.head(5))

display(perm_df.head(5))

payment_method_perm_importance = perm_df[
    perm_df['Feature'].str.contains('payment_method', case=False, na=False)
]

if not payment_method_perm_importance.empty:
    print("Payment method features in Permutation Importance:")
    display(payment_method_perm_importance)
else:
    print("No 'payment_method' features found in the permutation importance results.")

test_results = X_test.copy()
test_results['actual_returned'] = y_test
test_results['predicted_proba_return'] = y_proba_rf_tuned

high_risk_threshold = 0.5

high_risk_group = test_results[test_results['predicted_proba_return'] >= high_risk_threshold]

print(f"Number of orders in the high-risk group (predicted probability >= {high_risk_threshold}): {len(high_risk_group)}")

if not high_risk_group.empty:
    high_risk_return_rate = high_risk_group['actual_returned'].mean() * 100
    print(f"Actual Return Rate for the High-Risk Group: {high_risk_return_rate:.2f}%")
    display(high_risk_group.head())
else:
    print("No orders found in the high-risk group based on the defined threshold.")

import joblib
import os

if not os.path.exists('models'):
    os.makedirs('models')

model_filename = 'models/return_risk_model.pkl'
joblib.dump(best_rf_model, model_filename)

print(f"Model successfully saved to {model_filename}")